project:
  type: website
  output-dir: docs


website:
  title: "KIN 479: Human Motor Control"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Assignments
        menu:
          - href: assignments/pres.qmd
            text: Presentation Guidelines
          - href: assignments/pres-template.qmd
            text: Presentation Template
      - href: https://kin479-czqrgcuobnss5nxpjbp7tb.streamlit.app/  
        text: StudyApp

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true